
"use client"
import { useState } from "react";
import { FaQuestion } from "react-icons/fa";
import { GrPersonalComputer } from "react-icons/gr";
import { Target } from "phosphor-react";
import styles from "./about-us.module.scss";

const AboutUsPage = () => {
  const [activeSection, setActiveSection] = useState("who-are-we");

  const handleSectionChange = (section:string) => {
    setActiveSection(section);
  };

  return (
    <section className={styles["aboutus-container"]}>
      <div className="container">
        <h1 className="main-header">About Us</h1>
        <div className={styles["aboutus-items"]}>
            <div className={styles.btns}>
          <ul>
            <li
              className={
                activeSection === "who-are-we" ? styles.active : ""
              }
              onClick={() => handleSectionChange("who-are-we")}
            >
              <button
                aria-label="Who Are We"
                
              >
                <FaQuestion size={20} />
                <span>Who Are We</span>
              </button>
            </li>
            <li
              className={
                activeSection === "our-methodology" ? styles.active : ""
              }
              onClick={() => handleSectionChange("our-methodology")}
            >
              <button
                aria-label="Our Methodology"
              >
                <GrPersonalComputer size={20} />
                <span>Our Methodology</span>
              </button>
            </li>
            <li
              className={
                activeSection === "our-mission" ? styles.active : ""
              }
              onClick={() => handleSectionChange("our-mission")}
            >
              <button
                aria-label="Our Mission"
              
              >
                <Target size={20} />
                <span>Our Mission</span>
              </button>
            </li>
          </ul>
        </div>

        <div className={styles.details}>
          {activeSection === "who-are-we" && (
            <div>
              <h2>Who Are We</h2>
              <p>
                ECOSYST is a global leader in creating and deploying sustainable,
                innovative, and user-friendly solutions for various industries.
                Our team is comprised of experts in various fields, including
                technology, design, and business.
              </p>
            </div>
          )}
          {activeSection === "our-methodology" && (
            <div>
              <h2>Our Methodology</h2>
              <p>
                ECOSYST utilizes cutting-edge technology to create sustainable,
                innovative, and user-friendly solutions for various industries.
                Our methodology involves a combination of technology, expertise,
                and collaboration.
              </p>
            </div>
          )}
          {activeSection === "our-mission" && (
            <div>
              <h2>Our Mission</h2>
              <p>
                We assist industry and government leaders in developing and
                deploying these technological solutions. These partnerships
                reflect the body of work generated by ECOSYST, driven by the
                latest tools and technologies.
              </p>
            </div>
          )}
        </div>
        </div>
      </div>
    </section>
  );
};

export default AboutUsPage;