"use client"
import { useState } from "react";
import styles from "./our-philosophy.module.scss";
import { CurrencyDollar, Shuffle } from "phosphor-react";
import { IoShieldCheckmarkSharp } from "react-icons/io5";

const OurPhilosophy = () => {
  const [activeSection, setActiveSection] = useState("flexibility");

  const handleSectionChange = (section:string) => {
    setActiveSection(section);
  };
  return (
    <section className={styles["philosophy-container"]}>
      <div className="container">
        <h1 className="main-header">Our Philosophy</h1>
        <div className={styles["philosophy-items"]}>
          <div className={styles.btns}>
            <ul>
              <li
                className={activeSection === "flexibility" ? styles.active : ""}
                onClick={() => handleSectionChange("flexibility")}
              >
                <button aria-label="Flexibility">
                  <Shuffle size={20} />
                  <span>Flexibility</span>
                </button>
              </li>
              <li
                className={activeSection === "cost-saving" ? styles.active : ""}
                onClick={() => handleSectionChange("cost-saving")}
              >
                <button aria-label="Cost Saving">
                  <CurrencyDollar size={20} />
                  <span>Cost Saving</span>
                </button>
              </li>
              <li
                className={activeSection === "low-risk" ? styles.active : ""}
                onClick={() => handleSectionChange("low-risk")}
              >
                <button aria-label="low-risk">
                  <IoShieldCheckmarkSharp size={20} />
                  <span>Low Risk</span>
                </button>
              </li>
            </ul>
          </div>

          <div className={styles.details}>
            {activeSection === "flexibility" && (
              <div>
                <h2>Flexibility</h2>
                <p>
                  ECOSYST is a leading company in the sustainable technology and
                  design space. Our mission is to create innovative,
                  cost-effective, and sustainable solutions for the modern
                  world. We are committed to using technology to improve
                  efficiency, reduce waste, and create a more sustainable
                  future.
                </p>
              </div>
            )}
            {activeSection === "cost-saving" && (
              <div>
                <h2>Cost Saving</h2>
                <p>
                  ECOSYST is committed to reducing costs associated with
                  sustainable and innovative technologies. Our team of experts
                  in technology, design, and business is dedicated to developing
                  and deploying sustainable solutions that minimize costs and
                  improve efficiency.
                </p>
              </div>
            )}
            {activeSection === "low-risk" && (
              <div>
                <h2>Low Risk</h2>
                <p>
                  We assist industry and government leaders in developing and
                  deploying these technological solutions. These partnerships
                  reflect the body of work generated by ECOSYST, driven by the
                  latest tools and technologies.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default OurPhilosophy;
